version: 1.0.{build}
environment:
  Platform: Win32
  matrix:
  - PlatformToolset: LLVM-vs2014
    Configuration: Release
  - PlatformToolset: LLVM-vs2014
    Configuration: Debug
  - PlatformToolset: Default
    Configuration: Release
  - PlatformToolset: Default
    Configuration: Debug
matrix:
  allow_failures:
    - PlatformToolset: LLVM-vs2014
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: >-
    $toolset = If ($Env:PlatformToolset -ne "Default") {"/p:PlatformToolset=" + $Env:PlatformToolset} Else {""}

    $command = 'msbuild "vc14/columns_ui-public.sln" /m /verbosity:normal ' + $toolset +' /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

    iex $command

    $host.SetShouldExit($LASTEXITCODE)